import { Component } from '@angular/core';

@Component({
  selector: 'app-demo',
  imports: [],
  templateUrl: './demo.html',
  styleUrl: './demo.css',
})
export class Demo {
  // CUSTOMER & ORDER INFORMATION
  // Customer name fetched from logged-in user session or backend API
  customerName: string = 'Pranaya Rout';

  // Unique order identifier generated by the backend system
  orderId: string = 'ORD-10021';

  // Product selected by the customer
  productName: string = 'Angular Course - Full Stack Bundle';

  // PRICING DETAILS
  // Base price of a single product unit
  price: number = 4999;

  // Quantity selected by the user (can be changed from UI)
  quantity: number = 1;

  // CUSTOMER & PAYMENT STATUS FLAGS
  // Indicates whether the logged-in customer is a premium user
  // Used to apply special business rules such as discounts
  isPremiumCustomer: boolean = true;

  // Tracks whether payment is completed or still pending
  isPaymentDone: boolean = false;

  // BUSINESS LOGIC METHODS
  /*
    Calculates the final payable amount.
    - Multiplies price with quantity
    - Applies 20% discount if the customer is premium
    - Automatically recalculated whenever related data changes
  */
  getFinalAmount(): number {
    const total = this.price * this.quantity;               // Base total amount
    const discount = this.isPremiumCustomer ? total * 0.2 : 0; // Premium discount logic
    return total - discount;                                // Final amount after discount
  }

  /*
    Returns a user-friendly order status message.
    - Message changes automatically based on payment status
    - Demonstrates dynamic text rendering using Angular binding
  */
  getOrderStatusMessage(): string {
    return this.isPaymentDone
      ? `Payment received for order ${this.orderId}. Your order is confirmed`
      : `Payment pending for order ${this.orderId}. Please complete payment`;
  }
}




